# EKF configuration for a 2D robot with Wheel Odometry and IMU
# This is the standard and correct configuration.
ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true

    # The EKF will publish the odom->base_link transform
    publish_tf: true
    
    # Frame names
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # Sensor 0: Wheel Odometry from vehicle_driver
    # This provides our primary position and linear velocity estimate.
    odom0: /odom
    odom0_config:
      # We use X position, Y position, and Yaw rotation from this source.
      # The velocities are implicitly used by the filter's model.
      # [X, Y, Z, R, P, Y, Vx, Vy, Vz, VR, VP, VY, Ax, Ay, Az]
      [true,  true,  false,
       false, false, true,
       false, false, false,
       false, false, false,
       false, false, false]
    odom0_differential: false

    # Sensor 1: IMU from imu_publisher
    # This provides our rotational velocity correction.
    imu0: /imu/data
    imu0_config:
      # We ONLY use the rotational velocity around Z (Yaw rate) from the IMU.
      [false, false, false,
       false, false, false,
       false, false, false,
       false, false, true,
       false, false, false]
    imu0_differential: false
    imu0_remove_gravitational_acceleration: true
