# EKF configuration for the GLOBAL filter (map frame)
# This filter fuses the local odometry (from the first EKF) with the NAVIC/GPS data.
global_ekf_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    
    # We set the world frame to 'map' here. This filter is responsible for map->odom.
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: map

    # Sensor 0: Fused Odometry from the first EKF
    # It listens to the output of our first filter
    odom0: /odometry/filtered
    odom0_config:
      # Use X, Y position and Yaw rotation
      [true,  true,  false,
       false, false, true,
       false, false, false,
       false, false, false,
       false, false, false]
    odom0_differential: false

    # Sensor 1: NAVIC/GPS Data
    # It listens to the special odometry topic produced by navsat_transform_node
    odom1: /odometry/gps
    odom1_config:
      # Use ONLY X and Y position from the GPS
      # We do not use GPS heading as it's unreliable when stationary
      [true,  true,  false,
       false, false, false,
       false, false, false,
       false, false, false,
       false, false, false]
    odom1_differential: false